# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action_group',
        ),
        migrations.AddField(
            model_name='action',
            name='action_group',
            field=models.ManyToManyField(to='statistics.ActionGroup'),
        ),
    ]
