# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20151210_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_group',
            field=models.ManyToManyField(blank=True, to='statistics.ActionGroup'),
        ),
    ]
