# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

# Если получена ошибка
# "Key (action_id)=(0) is not present in table "statistics_action"."
# необходимо удалить все записи, у которых не заполнен action_id или client_id
#  выполнив запрос
# delete from statistics_clientactionlog where action_id is null or client_id is null


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_auto_20160119_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientactionlog',
            name='action',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='statistics.Action', verbose_name='\u0421\u043e\u0431\u044b\u0442\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientactionlog',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='statistics.Client', verbose_name='\u041a\u041c-\u043a\u043b\u0438\u0435\u043d\u0442'),
            preserve_default=False,
        ),
    ]
