# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 09:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawClientActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(verbose_name='UUID \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('action_uuid', models.UUIDField(verbose_name='UUID \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': '\u0421\u044b\u0440\u044b\u0435 \u0441\u043e\u0431\u044b\u0442\u0438\u0435 \u041a\u041c-\u043a\u043b\u0438\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u0421\u044b\u0440\u044b\u0435 \u0441\u043e\u0431\u044b\u0442\u0438\u044f \u041a\u041c-\u043a\u043b\u0438\u0435\u043d\u0442\u0430',
            },
        ),
    ]
