# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawclientactionlog',
            options={'verbose_name': '\u0421\u044b\u0440\u044b\u0435 \u0441\u043e\u0431\u044b\u0442\u0438\u0435 \u041a\u041c-\u043a\u043b\u0438\u0435\u043d\u0442\u0430', 'verbose_name_plural': '\u0421\u044b\u0440\u044b\u0435 \u0441\u043e\u0431\u044b\u0442\u0438\u044f \u041a\u041c-\u043a\u043b\u0438\u0435\u043d\u0442\u0430'},
        ),
    ]
