# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_statistics', '0002_auto_20160115_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawclientactionlog',
            name='processing_error',
            field=models.BooleanField(default=False, verbose_name='\u041e\u0448\u0438\u0431\u043a\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0438'),
        ),
    ]
